apiVersion: v1
kind: Service
metadata:
    name: "service-service-blog-golang"
    labels:
        app: "service-blog-golang"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
    selector:
        app: "service-blog-golang"